// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v6.32.0--rc2
// source: deleted.proto

package user_eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserDeleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventID   string                 `protobuf:"bytes,1,opt,name=EventID,proto3" json:"EventID,omitempty"`
	UserID    string                 `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Email     string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
}

func (x *UserDeleted) Reset() {
	*x = UserDeleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deleted_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleted) ProtoMessage() {}

func (x *UserDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_deleted_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleted.ProtoReflect.Descriptor instead.
func (*UserDeleted) Descriptor() ([]byte, []int) {
	return file_deleted_proto_rawDescGZIP(), []int{0}
}

func (x *UserDeleted) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *UserDeleted) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserDeleted) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDeleted) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_deleted_proto protoreflect.FileDescriptor

var file_deleted_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x01, 0x0a, 0x0b, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x38, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x63, 0x5a, 0x61, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61, 0x76, 0x73, 0x61, 0x6e, 0x61,
	0x6c, 0x62, 0x65, 0x72, 0x74, 0x6f, 0x76, 0x69, 0x63, 0x2d, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68,
	0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2d, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x6c, 0x2d, 0x6c, 0x69, 0x62, 0x2f, 0x74, 0x72, 0x65, 0x65, 0x2f, 0x6d, 0x61, 0x69, 0x6e,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x3b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_deleted_proto_rawDescOnce sync.Once
	file_deleted_proto_rawDescData = file_deleted_proto_rawDesc
)

func file_deleted_proto_rawDescGZIP() []byte {
	file_deleted_proto_rawDescOnce.Do(func() {
		file_deleted_proto_rawDescData = protoimpl.X.CompressGZIP(file_deleted_proto_rawDescData)
	})
	return file_deleted_proto_rawDescData
}

var file_deleted_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_deleted_proto_goTypes = []interface{}{
	(*UserDeleted)(nil),           // 0: events.UserDeleted
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_deleted_proto_depIdxs = []int32{
	1, // 0: events.UserDeleted.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_deleted_proto_init() }
func file_deleted_proto_init() {
	if File_deleted_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_deleted_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDeleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_deleted_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deleted_proto_goTypes,
		DependencyIndexes: file_deleted_proto_depIdxs,
		MessageInfos:      file_deleted_proto_msgTypes,
	}.Build()
	File_deleted_proto = out.File
	file_deleted_proto_rawDesc = nil
	file_deleted_proto_goTypes = nil
	file_deleted_proto_depIdxs = nil
}
