// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v6.32.0--rc2
// source: task.proto

package taskv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	TaskService_CreateTaskImage_FullMethodName = "/task.TaskService/CreateTaskImage"
	TaskService_GetTaskImages_FullMethodName   = "/task.TaskService/GetTaskImages"
	TaskService_GetTaskImage_FullMethodName    = "/task.TaskService/GetTaskImage"
	TaskService_UpdateTaskImage_FullMethodName = "/task.TaskService/UpdateTaskImage"
	TaskService_DeleteTaskImage_FullMethodName = "/task.TaskService/DeleteTaskImage"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskServiceClient interface {
	CreateTaskImage(ctx context.Context, in *CreateTaskImageRequest, opts ...grpc.CallOption) (*CreateTaskImageResponse, error)
	GetTaskImages(ctx context.Context, in *GetTaskImagesRequest, opts ...grpc.CallOption) (*GetTaskImagesResponse, error)
	GetTaskImage(ctx context.Context, in *GetTaskImageRequest, opts ...grpc.CallOption) (*GetTaskImageResponse, error)
	UpdateTaskImage(ctx context.Context, in *UpdateTaskImageRequest, opts ...grpc.CallOption) (*UpdateTaskImageResponse, error)
	DeleteTaskImage(ctx context.Context, in *DeleteTaskImageRequest, opts ...grpc.CallOption) (*DeleteTaskImageResponse, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) CreateTaskImage(ctx context.Context, in *CreateTaskImageRequest, opts ...grpc.CallOption) (*CreateTaskImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskImageResponse)
	err := c.cc.Invoke(ctx, TaskService_CreateTaskImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTaskImages(ctx context.Context, in *GetTaskImagesRequest, opts ...grpc.CallOption) (*GetTaskImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskImagesResponse)
	err := c.cc.Invoke(ctx, TaskService_GetTaskImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTaskImage(ctx context.Context, in *GetTaskImageRequest, opts ...grpc.CallOption) (*GetTaskImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskImageResponse)
	err := c.cc.Invoke(ctx, TaskService_GetTaskImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateTaskImage(ctx context.Context, in *UpdateTaskImageRequest, opts ...grpc.CallOption) (*UpdateTaskImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTaskImageResponse)
	err := c.cc.Invoke(ctx, TaskService_UpdateTaskImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteTaskImage(ctx context.Context, in *DeleteTaskImageRequest, opts ...grpc.CallOption) (*DeleteTaskImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTaskImageResponse)
	err := c.cc.Invoke(ctx, TaskService_DeleteTaskImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility
type TaskServiceServer interface {
	CreateTaskImage(context.Context, *CreateTaskImageRequest) (*CreateTaskImageResponse, error)
	GetTaskImages(context.Context, *GetTaskImagesRequest) (*GetTaskImagesResponse, error)
	GetTaskImage(context.Context, *GetTaskImageRequest) (*GetTaskImageResponse, error)
	UpdateTaskImage(context.Context, *UpdateTaskImageRequest) (*UpdateTaskImageResponse, error)
	DeleteTaskImage(context.Context, *DeleteTaskImageRequest) (*DeleteTaskImageResponse, error)
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTaskServiceServer struct {
}

func (UnimplementedTaskServiceServer) CreateTaskImage(context.Context, *CreateTaskImageRequest) (*CreateTaskImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTaskImage not implemented")
}
func (UnimplementedTaskServiceServer) GetTaskImages(context.Context, *GetTaskImagesRequest) (*GetTaskImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskImages not implemented")
}
func (UnimplementedTaskServiceServer) GetTaskImage(context.Context, *GetTaskImageRequest) (*GetTaskImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskImage not implemented")
}
func (UnimplementedTaskServiceServer) UpdateTaskImage(context.Context, *UpdateTaskImageRequest) (*UpdateTaskImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTaskImage not implemented")
}
func (UnimplementedTaskServiceServer) DeleteTaskImage(context.Context, *DeleteTaskImageRequest) (*DeleteTaskImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTaskImage not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_CreateTaskImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateTaskImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CreateTaskImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateTaskImage(ctx, req.(*CreateTaskImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTaskImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTaskImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTaskImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTaskImages(ctx, req.(*GetTaskImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTaskImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTaskImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTaskImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTaskImage(ctx, req.(*GetTaskImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateTaskImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateTaskImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_UpdateTaskImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateTaskImage(ctx, req.(*UpdateTaskImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteTaskImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteTaskImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_DeleteTaskImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteTaskImage(ctx, req.(*DeleteTaskImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTaskImage",
			Handler:    _TaskService_CreateTaskImage_Handler,
		},
		{
			MethodName: "GetTaskImages",
			Handler:    _TaskService_GetTaskImages_Handler,
		},
		{
			MethodName: "GetTaskImage",
			Handler:    _TaskService_GetTaskImage_Handler,
		},
		{
			MethodName: "UpdateTaskImage",
			Handler:    _TaskService_UpdateTaskImage_Handler,
		},
		{
			MethodName: "DeleteTaskImage",
			Handler:    _TaskService_DeleteTaskImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task.proto",
}
